get:
  x-eov-operation-id: getInstalledNodes
  x-eov-operation-handler: v1/handlers/installedNodes/installedNodes.handler
  tags:
    - Installed Nodes
  summary: Retrieve all installed nodes
  description: Retrieve all installed nodes from your instance.
  parameters:
    - $ref: '../../../../shared/spec/parameters/limit.yml'
    - $ref: '../../../../shared/spec/parameters/cursor.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/installedNodeList.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
